### ISSUE TITLE
Excellent app

### ISSUE THREAD

**Issue by pablopolanco6** [innovation-system/electron-kiosk#20]
I would like to know if there is a possibility to have multiple screens. For example, I have a PC with 4 screens and I would like to display a different URL in kiosk mode on different screens.

**Comment by robertsLando** [comment]
PR?

**Comment by pablopolanco6** [comment]
Can you work as a freelancer to make a modification to the app to detect the available screens and launch the URL to the selected screen?

**Comment by robertsLando** [comment]
@pablopolanco6 send me a PM at daniel.sorridi@gmail.com

**Comment by tomkyriacou64** [comment]
@pablopolanco6 @robertsLando I’d also be really keen for this feature, happy to chip in also 
Feel free to cc me in the email tomkyriacou64@gmail.com
